# Edyoda Numpy Assignment



## 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np

In [2]:
arr1 = np.zeros(10)

In [4]:
arr1[4] = 1

In [5]:
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 2. Create a vector with values ranging from 10 to 49.

In [6]:
arr2 = np.arange(10,50)

In [7]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
arr3 = np.arange(9).reshape(3,3)

In [11]:
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [13]:
arr4 = np.array([1,2,0,0,4,0])

In [16]:
np.where(arr4!=0)

(array([0, 1, 4], dtype=int64),)

## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [40]:
arr5 = np.random.randn(10,10)

In [41]:
arr5

array([[ 0.20237013,  1.27743212, -0.46245043, -0.89662649, -1.48478095,
         0.04914478, -0.67453579, -0.62337108,  0.5116595 ,  0.22497013],
       [ 0.74911126,  0.47071164,  1.74024312, -0.16205602,  1.21973126,
         0.77294551,  1.54168586, -0.22794722, -1.06995425, -1.26979836],
       [ 1.37662039, -1.03325542, -0.37669673,  0.88002582, -1.2255286 ,
        -0.83247848,  0.38922963, -1.28465977,  1.43469556, -0.04206161],
       [ 1.50828512,  1.22247653, -0.52776776,  0.44093558, -0.39143957,
         0.52772302, -2.70711374, -0.1753984 ,  0.80761761,  1.02822281],
       [ 0.30378555,  0.4504977 , -0.22861054,  0.36947899,  0.53620662,
         0.54033074, -1.17320979, -1.58324829, -0.1218207 , -0.60530057],
       [-0.49494133, -0.29361033, -0.00753193, -2.04138205,  0.72876006,
         0.73647621, -0.25087129, -0.35860838, -1.50115313, -1.08084324],
       [-0.66304831,  1.54793153,  0.35281024,  0.25747955,  1.04755693,
         1.37273625,  0.29551706, -0.02528104

In [42]:
arr5.max()

2.3850538453500465

In [43]:
arr5.min()

-2.7071137389959716

## 6. Create a random vector of size 30 and find the mean value.

In [48]:
arr6 = np.random.rand(30)

In [52]:
arr6

array([0.70940308, 0.91430385, 0.56173323, 0.07365674, 0.63862881,
       0.06268806, 0.66613036, 0.68448365, 0.24249413, 0.66335683,
       0.18505822, 0.07208583, 0.99556876, 0.26277295, 0.06046027,
       0.59320412, 0.42994854, 0.10971065, 0.12138683, 0.40040679,
       0.14308965, 0.10696613, 0.81872777, 0.30100035, 0.27952649,
       0.89882049, 0.63388505, 0.51658186, 0.95038829, 0.59967726])

In [51]:
arr6.mean()

0.4565381672956033